### ISSUE TITLE
Compilation issue on Mac OS 10.10.4

### ISSUE THREAD

**Issue by sardaukar** [char101/outliner#1]
Here's what I got

<pre>
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIC -DQT_USE_QSTRINGBUILDER -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I. -I3rdparty/hoedown/src -I/usr/local/Cellar/qt5/5.4.2/lib/QtWidgets.framework/Versions/5/Headers -I/usr/local/Cellar/qt5/5.4.2/lib/QtGui.framework/Versions/5/Headers -I/usr/local/Cellar/qt5/5.4.2/lib/QtSql.framework/Versions/5/Headers -I/usr/local/Cellar/qt5/5.4.2/lib/QtCore.framework/Versions/5/Headers -Ibuild/release/moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt5/5.4.2/mkspecs/macx-clang -F/usr/local/Cellar/qt5/5.4.2/lib -o build/release/obj/listmodel.o src/listmodel.cpp
In file included from src/listmodel.cpp:1:
src/listmodel.h:40:10: warning: 'ListModel::sort' hides overloaded virtual function [-Woverloaded-virtual]
    void sort(ListItem* parent, App::SortMode mode);
         ^
/usr/local/Cellar/qt5/5.4.2/lib/QtCore.framework/Versions/5/Headers/qabstractitemmodel.h:223:18: note: hidden overloaded virtual function
      'QAbstractItemModel::sort' declared here: type mismatch at 1st parameter ('int' vs 'ListItem *')
    virtual void sort(int column, Qt::SortOrder order = Qt::AscendingOrder);
                 ^
In file included from src/listmodel.cpp:3:
src/listtree.h:30:10: warning: 'ListTree::edit' hides overloaded virtual function [-Woverloaded-virtual]
    void edit(const QModelIndex& index);
         ^
/usr/local/Cellar/qt5/5.4.2/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h:281:18: note: hidden overloaded virtual function
      'QAbstractItemView::edit' declared here: different number of parameters (3 vs 1)
    virtual bool edit(const QModelIndex &index, EditTrigger trigger, QEvent *event);
                 ^
In file included from src/listmodel.cpp:3:
src/listtree.h:38:10: warning: 'ListTree::scrollTo' hides overloaded virtual function [-Woverloaded-virtual]
    void scrollTo(int itemId);
         ^
/usr/local/Cellar/qt5/5.4.2/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h:130:10: note: hidden overloaded virtual function 'QTreeView::scrollTo'
      declared here: different number of parameters (2 vs 1)
    void scrollTo(const QModelIndex &index, ScrollHint hint = EnsureVisible);
         ^
src/listmodel.cpp:144:33: warning: add explicit braces to avoid dangling else [-Wdangling-else]
                                else if (item->isCancelled())
                                ^
src/listmodel.cpp:226:12: error: no viable conversion from 'int' to 'Qt::ItemFlags' (aka 'QFlags<Qt::ItemFlag>')
    return flags;
           ^~~~~
/usr/local/Cellar/qt5/5.4.2/lib/QtCore.framework/Headers/qflags.h:86:7: note: candidate constructor (the implicit copy constructor) not viable: no known
      conversion from 'int' to 'const QFlags<Qt::ItemFlag> &' for 1st argument
class QFlags
      ^
/usr/local/Cellar/qt5/5.4.2/lib/QtCore.framework/Headers/qflags.h:86:7: note: candidate constructor (the implicit move constructor) not viable: no known
      conversion from 'int' to 'QFlags<Qt::ItemFlag> &&' for 1st argument
class QFlags
      ^
/usr/local/Cellar/qt5/5.4.2/lib/QtCore.framework/Headers/qflags.h:111:29: note: candidate constructor not viable: no known conversion from 'int' to
      'Qt::ItemFlag' for 1st argument
    Q_DECL_CONSTEXPR inline QFlags(Enum f) : i(Int(f)) {}
                            ^
/usr/local/Cellar/qt5/5.4.2/lib/QtCore.framework/Headers/qflags.h:112:29: note: candidate constructor not viable: no known conversion from 'int' to 'Zero'
      (aka 'int (QFlags<Qt::ItemFlag>::Private::*)') for 1st argument
    Q_DECL_CONSTEXPR inline QFlags(Zero = 0) : i(0) {}
                            ^
/usr/local/Cellar/qt5/5.4.2/lib/QtCore.framework/Headers/qflags.h:113:29: note: candidate constructor not viable: no known conversion from 'int' to 'QFlag'
      for 1st argument
    Q_DECL_CONSTEXPR inline QFlags(QFlag f) : i(f) {}
                            ^
/usr/local/Cellar/qt5/5.4.2/lib/QtCore.framework/Headers/qflags.h:116:29: note: candidate constructor not viable: no known conversion from 'int' to
      'std::initializer_list<ItemFlag>' for 1st argument
    Q_DECL_CONSTEXPR inline QFlags(std::initializer_list<Enum> flags)
                            ^
4 warnings and 1 error generated.
make: *** [build/release/obj/listmodel.o] Error 1
</pre>

Using Qt 5.4.2

**Comment by char101** [comment]
I think the issue is with clang. I never tried to compile it using clang though.

**Comment by sardaukar** [comment]
I changed the compiler CXXFLAGS to -std=c++11 and now I get this:

<pre>
DatabaseUtil::DatabaseUtil(const QString& dbPath): _dbPath(dbPath), _failed(false)
                                                   ^
src/databaseutil.cpp:286:40: error: reference to type 'const QString' could not bind to an rvalue of type 'char'
        newColumnsSpec << colSpec.join(' ');
                                       ^~~
/usr/local/Cellar/qt/4.8.7/include/QtCore/qstringlist.h:162:49: note: passing argument to parameter 'sep' here
inline QString QStringList::join(const QString &sep) const
                                                ^
src/databaseutil.cpp:291:87: error: reference to type 'const QString' could not bind to an rvalue of type 'char'
    sql.prepare(QString("CREATE TABLE %0 (%1)").arg(newTable).arg(newColumnsSpec.join(',')));
                                                                                      ^~~
/usr/local/Cellar/qt/4.8.7/include/QtCore/qstringlist.h:162:49: note: passing argument to parameter 'sep' here
inline QString QStringList::join(const QString &sep) const
                                                ^
1 warning and 2 errors generated.
make: *** [build/release/obj/databaseutil.o] Error 1
</pre>

I understand it's not the compiler you use, but you have a willing tester if you want to ever support it :D

**Comment by char101** [comment]
If I want to compile with clang then the problem is that I have to compile Qt first which takes a very long time.

Also as you may have probably noticed that this project is in hiatus. I don't feel like it solves the complexity of task management.

**Comment by sardaukar** [comment]
I have Qt installed already, by using something called Homebrew (http://brew.sh), so it's just outliner that needs to be compiled. But I understand the hiatus - too bad, it seems like a great project :/
